version: '3.8'

services:
  node0:
    container_name: gokite-chain-node
    image: gokite-chain:latest
    volumes:
      - ./data:/data
      # - ./config:/config
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - 9650:9650
      - 9651:9651
    environment:
      - AVAGO_DATA_DIR=/data
      - AVAGO_HTTP_ALLOWED_HOSTS=*
      - AVAGO_HTTP_HOST=0.0.0.0
      - AVAGO_HTTP_PORT=9650
      - AVAGO_LOG_LEVEL=info
      - AVAGO_NETWORK_ID=mainnet
      - AVAGO_PARTIAL_SYNC_PRIMARY_NETWORK=true
      - AVAGO_PUBLIC_IP_RESOLUTION_SERVICE=ifconfigCo
      - AVAGO_STAKING_PORT=9651
      - PLUGIN_ID=pJhESDWpZttEG5zDJpoZWR14EsYdZw8JNc2xReUF35cQJCgAy
      # - AVAGO_CHAIN_CONFIG_DIR=/config
      # - KITE_CHAIN_ID=nQ9iPT7ZQQx1qwBTs68EGiU8cu1GHMMjzvYktmA3oRs4esg3V
      # - AVAGO_PLUGIN_DIR=/plugins
      # - AVAGO_TRACK_SUBNETS=
      

